### PR TITLE
1.21 port

### PR DESCRIPTION
**Pull request by jquann1998**
Ported to 1.21

### CODE REVIEW

**Comment by jquann1998** [comment]
I actually did it in a partial manner.

**Comment by baguchi** [comment]
Please stop sending pull requests for partial improvements just to get them ported to 1.21.
EarthMobs will definitely be on 1.21, so please stop doing that because it will just make things more difficult.

**Comment by jquann1998** [comment]
> Please stop sending pull requests for partial improvements just to get them ported to 1.21.

Why are you like this? I just wanted to help you port things to the latest version. That's all.

**Comment by baguchi** [comment]
okey fine

**Comment by jquann1998** [comment]
I should've asked for permission before I port it partially though by the way.

**Comment by Polarice3** [comment]
> > Please stop sending pull requests for partial improvements just to get them ported to 1.21.
> 
> Why are you like this? I just wanted to help you port things to the latest version. That's all.

Why are you like this? He said stop and you're acting like you own him or something.

**Comment by jquann1998** [comment]
> Why are you like this? He said stop and you're acting like you own him or something.

It's because I'm trying to port the EarthMobs mod to 1.21, OK?

**Comment by Polarice3** [comment]
> > Why are you like this? He said stop and you're acting like you own him or something.
> 
> It's because I'm trying to port the EarthMobs mod to 1.21, OK?

And how is being rude and demanding gonna help with that? As Bagu said, you're just making things more difficult for him. This is his project, so stop being a jerk.

**Pull request merged**
